# Generated by Django 4.2 on 2023-04-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contrasenia', models.CharField(max_length=20)),
                ('nombre_usuario', models.CharField(max_length=25, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
    ]

