# Generated by Django 4.2 on 2023-04-10 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacion', '0002_posteo_remove_persona_contrasenia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='autor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
