# Generated by Django 4.2 on 2023-04-11 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_posteo_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='Posteo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.posteo'),
            preserve_default=False,
        ),
    ]
