# Generated by Django 4.2 on 2023-04-11 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_comentario_posteo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='Posteo',
            new_name='posteo',
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
