# Generated by Django 4.2 on 2023-04-11 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacion', '0005_rename_posteo_comentario_posteo_comentario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.persona')),
                ('imagen', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
