# Generated by Django 4.2 on 2023-04-11 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacion', '0006_alter_persona_descripcion_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='imagen',
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mi_blog', models.CharField(max_length=400)),
                ('descripcion', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.persona')),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
