# Generated by Django 4.2 on 2023-04-11 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_remove_perfil_descripcion_remove_perfil_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='habilidades',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='detalle',
            name='otros_proyectos',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='descripcion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.persona'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='mi_blog',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
