# Generated by Django 4.1.7 on 2023-04-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_alter_detalle_descripcion_alter_detalle_habilidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='descripcion',
            field=models.CharField(blank=True, default='Ingrese aquí sus proyectos', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
